name: Create vCluster

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        required: true
        type: string
      namespace:
        required: true
        type: string

jobs:
  create-vcluster:
    runs-on: ubuntu-latest

    steps:
      - name: Install vCluster CLI
        run: |
          curl -LO https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64
          chmod +x vcluster-linux-amd64
          sudo mv vcluster-linux-amd64 /usr/local/bin/vcluster

      - name: Set up Kube context (you handle this part)
        run: |
          # Example: export KUBECONFIG from secret or EKS config
          echo "Assume kube context setup here"

      - name: Create vCluster
        run: |
          vcluster create "${{ github.event.inputs.cluster_name }}" -n "${{ github.event.inputs.namespace }}"
